PlaySound=AltPlaySound
CheckerBean=AltCheckerBean
CheckerBeanTest=AltCheckerBeanTest
ControllerBean=AltControllerBean
CurTimeBean=AltCurTimeBean
PointBean=AltPointBean
BigDecimalConverter=AltBigDecimalConverter
BigDecimalRangeValidator=AltBigDecimalRangeValidator
PointDAO=AltPointDAO
Main=AltMain