PlaySound=AltPlaySound
CheckerBean=AltCheckerBean
ControllerBean=AltControllerBean
CurTimeBean=AltCurTimeBean
# PointBean=AltPointBean
BigDecimalConverter=AltBigDecimalConverter
BigDecimalRangeValidator=AltBigDecimalRangeValidator
# PointDAO=AltPointDAO
Point=AltPoint
Main=AltMain