# папочки
build.dir=build/classes
build.test.dir=build/test-classes
src.dir=src/main
src.test.dir=src/test
src.general.dir=src
lib.dir=lib
res.dir=src/main/resources
art.dir=artifacts
test.reports.dir=build/test-reports
current.dir=.
webcontent.dir=src/main/webapp
wildfly.deploy.dir=wildfly-37.0.1.Final/standalone/deployments
antresources.dir=ant-resources
remote.dir=~/opi3/deployed
mf.dir=build/MANIFEST.MF
javadoc.dir=javadoc

webinf.classes.dir=WEB-INF/classes

war.name=ROOT.war
webxml.dest=WEB-INF/web.xml
persistence.path=META-INF/persistence.xml
build.music.path=oi-oi-oe-oi-a-eye-eye_tUunIyy.wav
soundplayer.package=com.ldpst.ant.PlaySound

project.name=web-lab-3
manifest.version=1.0
project.version=1.0.0
main.class=com.ldpst.Main

svn.repo.url=file:///D:/Projects/java/opi_lab3_svn/repo
svn.rev.dir=svn-revs
work.dir=work_team

temp.dir=tmp
alt.backup.dir=${temp.dir}/backup-src
alt.work.dir=${temp.dir}/alt-src
alt.replace.file=${antresources.dir}/alt-replace.properties